from dotenv import dotenv_values

credentials = dotenv_values(".env.secret")
params = dotenv_values(".env.params")

BOT_TOKEN = credentials["BOT_API_TOKEN"]

CHART_URL = params["CHART_URL"]
CHART_ELEMENT_SELECTOR = params["CHART_ELEMENT_SELECTOR"]
LOADED_CHART_ELEMENT_SELECTOR = params["LOADED_CHART_ELEMENT_SELECTOR"]
BLUR_ELEMENT_SELECTOR = params["BLUR_ELEMENT_SELECTOR"]
LOADER_SPINNER_SELECTOR = params["LOADER_SPINNER_SELECTOR"]
CONSENT_ROOT_ELEMENT_SELECTOR = params["CONSENT_ROOT_ELEMENT_SELECTOR"]
SYMBOL_DROPDOWN_BUTTON_SELECTOR = params["SYMBOL_DROPDOWN_BUTTON_SELECTOR"]
DROPDOWN_LIST_ELEMENT_SELECTOR = params["DROPDOWN_LIST_ELEMENT_SELECTOR"]
DOWNLOAD_CHART_BUTTON_SELECTOR = params["DOWNLOAD_CHART_BUTTON_SELECTOR"]

WEBPAGE_WIDTH = int(params["WEBPAGE_WIDTH"])
CHART_X_OFFSET = int(params["CHART_X_MARGIN"])
CHART_Y_OFFSET = int(params["CHART_Y_MARGIN"])

CHART_DELAY_SECONDS = int(params["CHART_DELAY_SECONDS"])
