from dotenv import dotenv_values

credentials = dotenv_values(".env.secret")
params = dotenv_values(".env.params")

BOT_TOKEN = credentials["BOT_API_TOKEN"]

CHART_URL = params["CHART_URL"]
CHART_ELEMENT_SELECTOR = params["CHART_ELEMENT_SELECTOR"]
CONSENT_ROOT_ELEMENT_SELECTOR = params["CONSENT_ROOT_ELEMENT_SELECTOR"]
SYMBOL_TOGGLE_BUTTON_SELECTOR = params["SYMBOL_TOGGLE_BUTTON_SELECTOR"]
SYMBOL_DROPDOWN_BUTTON_SELECTOR = params["SYMBOL_DROPDOWN_BUTTON_SELECTOR"]
DROPDOW_LIST_ELEMENT_SELECTOR = params["DROPDOW_LIST_ELEMENT_SELECTOR"]

WEBPAGE_WIDTH = int(params["WEBPAGE_WIDTH"])
