from dotenv import dotenv_values

credentials = dotenv_values(".env.secret")
params = dotenv_values(".env.params")

BOT_TOKEN = credentials["BOT_API_TOKEN"]
COINGLASS_EMAIL = credentials["COINGLASS_EMAIL"]
COINGLASS_PASSWORD = credentials["COINGLASS_PASSWORD"]


CHART_URL = params["CHART_URL"]
LOGIN_URL = params["LOGIN_URL"]
CHART_ELEMENT_SELECTOR = params["CHART_ELEMENT_SELECTOR"]
BLUR_ELEMENT_SELECTOR = params["BLUR_ELEMENT_SELECTOR"]
LOADER_SPINNER_SELECTOR = params["LOADER_SPINNER_SELECTOR"]
CONSENT_ROOT_ELEMENT_SELECTOR = params["CONSENT_ROOT_ELEMENT_SELECTOR"]
SYMBOL_DROPDOWN_BUTTON_SELECTOR = params["SYMBOL_DROPDOWN_BUTTON_SELECTOR"]
DROPDOWN_LIST_ELEMENT_SELECTOR = params["DROPDOWN_LIST_ELEMENT_SELECTOR"]
DOWNLOAD_CHART_BUTTON_SELECTOR = params["DOWNLOAD_CHART_BUTTON_SELECTOR"]
LOGGED_OUT_INDICATOR_SELECTOR = params["LOGGED_OUT_INDICATOR_SELECTOR"]
EMAIL_FIELD_SELECTOR = params["EMAIL_FIELD_SELECTOR"]
PASSWORD_FIELD_SELECTOR = params["PASSWORD_FIELD_SELECTOR"]
LOGIN_SUBMIT_BUTTON_SELECTOR_XPATH = params["LOGIN_SUBMIT_BUTTON_SELECTOR_XPATH"]

WEBPAGE_WIDTH = int(params["WEBPAGE_WIDTH"])
CHART_X_OFFSET = int(params["CHART_X_MARGIN"])
CHART_Y_OFFSET = int(params["CHART_Y_MARGIN"])

CHART_DELAY_SECONDS = int(params["CHART_DELAY_SECONDS"])
